#!/bin/bash

tmp=/tmp/$$
dir=$(dirname $0)

grep . *.summary     |
sed 's/\.summary/ /' |
tr -d :              |
sort                 |
while read day item num ; do
	date "+%Y %j $item $num" -d $day
done                 |
awk '{print $1"."$2/366, $3, $4}' |
sed 's/\.0//'        |
awk -v tmp=$tmp '{print $1, $3 > tmp"-"$2}'

cat $tmp-OK
cat $tmp-NG
cat $tmp-DNF
cat $tmp-DIFF_LINES

gnuplot << EOF
set terminal png
set output "$dir/graph.png"
set title "TEST RESULTS using run-* SCRIPTS in OFFICIAL BASH REPO (alpha branch)"
set xrange [2025:2026]
set xtics 1
set mxtics 4
set yrange [0:90]
set ytics nomirror
set y2range [0:80000]
set y2tics 20000
plot '$tmp-OK' title "PASSED run-* FILES (LEFT Y-AXIS)" axis x1y1 with linespoints pt 2 lc 1,\
'$tmp-NG' title "NOT PASSED run-* FILES (LEFT Y-AXIS)" axis x1y1 with linespoints pt 1 lc 2,\
'$tmp-DNF' axis x1y1 title "DNF run-* FILES (LEFT Y-AXIS)" with linespoints pt 3 lc 3, \
'$tmp-DIFF_LINES' axis x1y2 title "TOTAL LINES of DIFF (RIGHT Y-AXIS)" with linespoints pt 4 lc 4
EOF
