#!/bin/bash

sushdir=~/GIT/rusty_bash
testdir=~/GIT/bash/tests
export PATH=$PATH:/home/ueda/GIT/bash/tests

( cd $sushdir && cargo build --release) || exit 1 

export THIS_SH="${sushdir}/target/release/sush -b"

cd $testdir || exit 1

BASH_TSTOUT=/tmp/$$-$t bash $1
